import type { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";
import { TerminalProvider } from "./_components/terminal/TerminalContext";
import Footer from "./_components/layout/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full flex flex-col bg-[#181a20]`}
        style={{
          background:
            "radial-gradient(ellipse at 60% 20%, #23272e 0%, #181a20 100%)",
          minHeight: "100vh",
        }}
      >
        <TerminalProvider>
          {/* macOS window frame (신호등 바) */}
          <div className="w-full h-9 bg-[#23272e] border-b border-[#22242a] flex items-center px-4 fixed top-0 left-0 z-40">
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-[#ff5f56] border border-[#e0443e] shadow-inner" />
              <span className="w-3 h-3 rounded-full bg-[#ffbd2e] border border-[#dea123] shadow-inner" />
              <span className="w-3 h-3 rounded-full bg-[#27c93f] border border-[#13a10e] shadow-inner" />
            </div>
            <span className="ml-4 text-sm text-[#cccccc] font-medium tracking-wide select-none">
              CodeTune Music
            </span>
          </div>
          {/* VSCode 전체 레이아웃: 사이드바+에디터 */}
          <div className="flex flex-1 min-h-0 min-w-0 h-[calc(100vh-2rem)] pt-9">
            {children}
          </div>
          {/* VSCode 스타일 푸터 (상태바) - 터미널이 열려있을 때는 숨김 */}
          <Footer />
        </TerminalProvider>
      </body>
    </html>
  );
}
